package com.nuitcode.daytesk.server

import java.net.URI
import java.sql.Connection
import java.sql.DriverManager

object Database {
    fun connect(): Connection {
        val url = Env.databaseUrl
        return if (url.isBlank()) {
            Class.forName("org.h2.Driver")
            DriverManager.getConnection("jdbc:h2:mem:daytesk;MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "")
        } else {
            Class.forName("org.postgresql.Driver")
            val jdbc = toJdbc(url)
            DriverManager.getConnection(jdbc.url, jdbc.user, jdbc.password)
        }
    }

    fun migrate(connection: Connection) {
        connection.createStatement().use { statement ->
            statement.execute(
                """
                CREATE TABLE IF NOT EXISTS users (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    email TEXT NOT NULL UNIQUE,
                    username TEXT NOT NULL UNIQUE,
                    display_name TEXT NOT NULL,
                    password_hash TEXT NOT NULL
                )
                """.trimIndent(),
            )
        }
        SyncRepository.migrate(connection)
    }

    private data class Jdbc(val url: String, val user: String, val password: String)

    private fun toJdbc(raw: String): Jdbc {
        val normalized = raw.replace(Regex("^postgres(ql)?://"), "http://")
        val uri = URI(normalized)
        val userInfo = uri.userInfo?.split(":", limit = 2) ?: listOf("", "")
        val user = java.net.URLDecoder.decode(userInfo.getOrElse(0) { "" }, Charsets.UTF_8)
        val password = java.net.URLDecoder.decode(userInfo.getOrElse(1) { "" }, Charsets.UTF_8)
        val host = uri.host
        val port = if (uri.port > 0) uri.port else 5432
        val database = uri.path.trim('/').ifBlank { "neondb" }
        val query = (uri.query ?: "sslmode=require")
            .split("&")
            .filter { it.isNotBlank() && !it.startsWith("channel_binding", ignoreCase = true) }
            .joinToString("&")
            .ifBlank { "sslmode=require" }
        return Jdbc(
            url = "jdbc:postgresql://$host:$port/$database?$query",
            user = user,
            password = password,
        )
    }
}
